### ISSUE TITLE
"Functional Programming With Numbers" example doesn't compile

### ISSUE THREAD

**Issue by crumblingstatue** [mmstick/phoronix-reader#2]
- `RangeFrom` doesn't have an `.iter()` method. Instead, it directly implements `Iterator`.
- Collecting into a `Vec` needs a type hint.
- `Vec` doesn't implement `Display`, so it can't be printed with `{}`, one should use `{:?}`.

Also, `1..` isn't a "Vector", it is a range.

The example should look something like this:

``` rust
fn main() {
    let vector = (1..)          // Infinite range of integers starting from 1
        .filter(|x| x % 2 != 0) // Only yield odd numbers
        .take(5)                // Take only five numbers
        .map(|x| x * x)         // Square each number
        .collect::<Vec<_>>();   // Collect into a Vec
    println!("{:?}", vector);   // Print result
}

```

**Comment by mmstick** [comment]
Fixed
