### ISSUE TITLE
Needless conversion in `open_testing` in chapter 4

### ISSUE THREAD

**Issue by crumblingstatue** [mmstick/phoronix-reader#3]
> Because a &str has a lifetime that won't live beyond the function call, we will convert it into a String with String::from().

This is not true. `include_str!()` returns `&'static str`, which has the `static` lifetime, which outlives every other lifetime.

The code can simply be:

``` Rust
fn open_testing() -> &'static str {
    include_str!("phoronix.html")
}
```

Also, `open_testing` isn't a very accurate name, as it doesn't really open anything at runtime. It just returns a string which is already present in memory.

A better name would be `testing_html`, as it simply returns the contents of the testing copy of `phoronix.html`.

**Comment by mmstick** [comment]
Issue has been resolved.
